name: Slack notification wrapper
description: Some automation
inputs:
  channel:
    description: Slack channel ID
    required: true
  username:
    description: Slack username
    required: false
    default: github-actions
  icon_url:
    description: Slack icon url
    required: false
    default: https://avatars.githubusercontent.com/in/15368?v=4
  text:
    description: Block text
    required: true
  attachment_text:
    description: Attachment text
    required: false
  SLACK_WEBHOOK_URL:
    required: true
runs:
  using: "composite"
  steps:
  - name: Slack notification
    uses: 8398a7/action-slack@v3
    env:
      SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
    with:
      status: custom
      custom_payload: |
        {
          channel: "${{ inputs.channel }}",
          username: "${{ inputs.username }}",
          icon_url: "${{ inputs.icon_url }}",
          blocks: [
            {
              type: "section",
              text: {
                type: "mrkdwn",
                text: ${{ toJSON(inputs.text) }},
              }
            },
          ],
          ${{ inputs.attachment_text && format('attachments: [{text: {0}}],', toJSON(inputs.attachment_text)) }}
        }